HOTFIX: Fix Python syntax error in JavaScript click code
ERROR: f-string expression part cannot include a backslash

The previous commit had a syntax error that prevented app startup:
selector.replace("'", "\\'" ) inside f-string is not allowed in Python

FIXED: Move the replacement outside the f-string:
safe_selector = selector.replace("'", "\\'" )
js_code = f'... {safe_selector} ...'

This was causing Railway deployment healthcheck to fail because
the app couldn't start due to SyntaxError.